[package]
name = "poketerm"
version = "0.1.0"
authors = ["Ryan Kembrey <ryan.kembrey@student.uts>"]
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
ratatui = "0.26.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
